-- Copyright (C) 2026 Danny Nunez

local output = script.dir .. "/../artifacts/phase4-v3/"
local start_frame = nil

local function shot(name)
  local display_control = emu:read16(0x04000000)
  local page = 0x06000000
  if math.floor(display_control / 0x10) % 2 == 1 then
    page = page + 0xA000
  end
  local frame = assert(io.open(output .. name .. ".frame", "wb"))
  frame:write(emu:readRange(0x05000000, 512))
  frame:write(emu:readRange(page, 240 * 160))
  frame:close()
end

local function press(key) emu:addKey(key) end
local function release(key) emu:clearKey(key) end

callbacks:add("frame", function()
  if not start_frame then start_frame = emu:currentFrame() end
  local frame = emu:currentFrame() - start_frame

  if frame == 120 then shot("browse-aurora-ready")
  elseif frame == 130 then press(C.GBA_KEY.DOWN)
  elseif frame == 135 then release(C.GBA_KEY.DOWN)
  elseif frame == 145 then shot("browse-checker-pending")
  elseif frame == 200 then shot("browse-checker-ready")
  elseif frame == 210 then shot("browse-checker-stable")
  elseif frame == 215 then press(C.GBA_KEY.DOWN)
  elseif frame == 220 then release(C.GBA_KEY.DOWN)
  elseif frame == 310 then shot("browse-missing")
  elseif frame == 315 then press(C.GBA_KEY.DOWN)
  elseif frame == 320 then release(C.GBA_KEY.DOWN)
  elseif frame == 410 then shot("browse-invalid")
  elseif frame == 415 then press(C.GBA_KEY.DOWN)
  elseif frame == 420 then release(C.GBA_KEY.DOWN)
  elseif frame == 510 then shot("browse-folder")
  elseif frame == 515 then press(C.GBA_KEY.DOWN)
  elseif frame == 520 then release(C.GBA_KEY.DOWN)
  elseif frame == 530 then shot("browse-long-name-start")
  elseif frame == 610 then shot("browse-long-name-scrolled")
  elseif frame == 615 then press(C.GBA_KEY.DOWN)
  elseif frame == 620 then release(C.GBA_KEY.DOWN)
  elseif frame == 630 then shot("browse-last-row")
  elseif frame == 635 then press(C.GBA_KEY.DOWN)
  elseif frame == 640 then release(C.GBA_KEY.DOWN)
  elseif frame == 650 then shot("browse-window-shift")

  elseif frame == 655 then press(C.GBA_KEY.L)
  elseif frame == 660 then release(C.GBA_KEY.L)
  elseif frame == 720 then shot("recent-aurora-ready")
  elseif frame == 725 then press(C.GBA_KEY.L)
  elseif frame == 730 then release(C.GBA_KEY.L)
  elseif frame == 790 then shot("favorites-empty")
  elseif frame == 795 then press(C.GBA_KEY.R)
  elseif frame == 800 then release(C.GBA_KEY.R)
  elseif frame == 805 then press(C.GBA_KEY.R)
  elseif frame == 810 then release(C.GBA_KEY.R)
  elseif frame == 815 then press(C.GBA_KEY.R)
  elseif frame == 820 then release(C.GBA_KEY.R)
  elseif frame == 880 then shot("tools-home")
  elseif frame == 885 then press(C.GBA_KEY.A)
  elseif frame == 890 then release(C.GBA_KEY.A)
  elseif frame == 930 then shot("appearance-electric-blue-grid")

  elseif frame == 935 then press(C.GBA_KEY.DOWN)
  elseif frame == 940 then release(C.GBA_KEY.DOWN)
  elseif frame == 945 then press(C.GBA_KEY.LEFT)
  elseif frame == 950 then release(C.GBA_KEY.LEFT)
  elseif frame == 955 then press(C.GBA_KEY.LEFT)
  elseif frame == 960 then release(C.GBA_KEY.LEFT)
  elseif frame == 970 then shot("wallpaper-none")
  elseif frame == 975 then press(C.GBA_KEY.RIGHT)
  elseif frame == 980 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1000 then shot("wallpaper-weave")
  elseif frame == 1005 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1010 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1030 then shot("wallpaper-grid")
  elseif frame == 1035 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1040 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1060 then shot("wallpaper-circuit")

  elseif frame == 1095 then press(C.GBA_KEY.UP)
  elseif frame == 1100 then release(C.GBA_KEY.UP)
  elseif frame == 1105 then press(C.GBA_KEY.LEFT)
  elseif frame == 1110 then release(C.GBA_KEY.LEFT)
  elseif frame == 1130 then shot("preset-chrome-silver")
  elseif frame == 1135 then press(C.GBA_KEY.LEFT)
  elseif frame == 1140 then release(C.GBA_KEY.LEFT)
  elseif frame == 1170 then shot("preset-stealth-black")
  elseif frame == 1175 then press(C.GBA_KEY.LEFT)
  elseif frame == 1180 then release(C.GBA_KEY.LEFT)
  elseif frame == 1210 then shot("preset-mutant-green")

  elseif frame == 1215 then press(C.GBA_KEY.DOWN)
  elseif frame == 1220 then release(C.GBA_KEY.DOWN)
  elseif frame == 1225 then press(C.GBA_KEY.DOWN)
  elseif frame == 1230 then release(C.GBA_KEY.DOWN)
  elseif frame == 1235 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1240 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1260 then shot("custom-background")
  elseif frame == 1265 then press(C.GBA_KEY.DOWN)
  elseif frame == 1270 then release(C.GBA_KEY.DOWN)
  elseif frame == 1275 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1280 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1300 then shot("custom-accent")
  elseif frame == 1305 then press(C.GBA_KEY.DOWN)
  elseif frame == 1310 then release(C.GBA_KEY.DOWN)
  elseif frame == 1315 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1320 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1340 then shot("custom-selection")
  elseif frame == 1345 then press(C.GBA_KEY.DOWN)
  elseif frame == 1350 then release(C.GBA_KEY.DOWN)
  elseif frame == 1355 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1360 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1380 then shot("contrast-dark")
  elseif frame == 1385 then press(C.GBA_KEY.RIGHT)
  elseif frame == 1390 then release(C.GBA_KEY.RIGHT)
  elseif frame == 1410 then shot("contrast-light")
  elseif frame == 1415 then press(C.GBA_KEY.DOWN)
  elseif frame == 1420 then release(C.GBA_KEY.DOWN)
  elseif frame == 1425 then press(C.GBA_KEY.A)
  elseif frame == 1430 then release(C.GBA_KEY.A)
  elseif frame == 1450 then shot("theme-reset")
  elseif frame == 1455 then press(C.GBA_KEY.B)
  elseif frame == 1460 then release(C.GBA_KEY.B)
  elseif frame == 1490 then shot("tools-after-save")
  elseif frame == 1500 then
    local marker = io.open(output .. "complete.txt", "w")
    marker:write("mGBA Phase 4 v3 demo completed\n")
    marker:close()
  end
end)
